### ISSUE TITLE
First Review of Methods Chapter

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#1]
Here is the pdf of the report, the methods chapter is labeled such in the table of contents.

[main.pdf](https://github.com/ZoeRichter/master-thesis/files/6062470/main.pdf)

**Comment by katyhuff** [comment]
[zoe-ms.pdf](https://github.com/ZoeRichter/master-thesis/files/6087093/zoe-ms.pdf)
