### ISSUE TITLE
Lit Review and Methods Second Review

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#10]
I've got the next draft of the method and lit review chapters completed and ready for review.  Figures should all be at an appropriate size and location.  I also redid some of the figures in methods, they are all to scale now!

pdf is [here](https://github.com/ZoeRichter/master-thesis/blob/master/main.pdf).  If the other chapters get feedback and get finished up tomorrow, any changes I make wouldn't be to methods/lit review, so even an "updated" pdf should be fine to review.

Also, @munkm

**Comment by katyhuff** [comment]
Closing this since I believe it is, as they say, [OBE](https://www.merriam-webster.com/dictionary/overtaken%20by%20events).
