### ISSUE TITLE
Second Draft Review

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#11]
I have completed the first round of edits (thank you Nathan) and have pushed the updated report pdf, [here](https://github.com/ZoeRichter/master-thesis/blob/master/main.pdf).

Also, @munkm

I believe I have completed all the sections, though I do still need a snazzy title.

**Comment by ZoeRichter** [comment]
I have updated this draft after going through the writing checklist, see #14

**Comment by munkm** [comment]
here is my review [munkmreview-richter_masters.pdf](https://drive.google.com/file/d/1JV91S_WwIN_9vNjZAwGML8bcenDRIOtl/view?usp=sharing)

**Comment by katyhuff** [comment]
Closing this since I believe it is, as they say, [OBE](https://www.merriam-webster.com/dictionary/overtaken%20by%20events).

**Comment by katyhuff** [comment]
Closing this since I believe it is, as they say, [OBE](https://www.merriam-webster.com/dictionary/overtaken%20by%20events).
