### ISSUE TITLE
First review of lit review first draft

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#2]
I've finished the first draft of my lit review.  I left some notes at the top of things I wanted to get some feedback on for sure.  Starts at page 3.  Thank you!

[main.pdf](https://github.com/ZoeRichter/master-thesis/files/6247618/main.pdf)

**Comment by katyhuff** [comment]
Lit review initial review here:

[2021-04-02-zoe.pdf](https://github.com/ZoeRichter/master-thesis/files/6281250/2021-04-02-zoe.pdf)
