### ISSUE TITLE
Licensing Update

### ISSUE THREAD

**Issue by nsryan2** [ZoeRichter/master-thesis#5]
Everything is automatically licensed under creative commons, but it might be useful to have a CC-By-4.0. If I'm remembering correctly, this is what we ended up using for Andre's Thesis and it complied with the school's guidelines. I had to make it a .txt file to upload it here. Just something to consider, depending on how you generated the figures, you might have to explore other types of license but from what I can tell that's not the case.
[CC-BY-4.0.txt](https://github.com/ZoeRichter/master-thesis/files/6578233/CC-BY-4.0.txt)

**Comment by ZoeRichter** [comment]
Thanks Nathan, I've added the license you suggested!
