### ISSUE TITLE
Lit Review...review.

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#6]
Hi Nathan!  Could you review the lit review chapter for me? (chapter 2).  I know the one figure isn't fitting well with the rest of the chapter, but I'm going to wait until the text is more finalized so I know what I have to work with.

Just checking the writing checklist should be enough.  Beyond that, I think I've got my sections organized alright, but if you have a suggestion of a better order, I'm all ears :).

Thanks again!

[main.pdf](https://github.com/ZoeRichter/master-thesis/files/6593809/main.pdf)

**Comment by nsryan2** [comment]
Sure thing! I'll get to it today

**Comment by nsryan2** [comment]
Hey @ZoeRichter, I finished the lit review... review, and attached it to this comment. I couldn't remember if I emailed it to you last time, if there's a better way to send this just let me know!
[Lit_review_nr.pdf](https://github.com/ZoeRichter/master-thesis/files/6612464/Lit_review_nr.pdf)

**Comment by ZoeRichter** [comment]
I received the pdf via slack, thanks!
