### ISSUE TITLE
Results Review

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#7]
Hi Nathan, could you review the results chapter for me?  I'll include the pdf [here](https://github.com/ZoeRichter/master-thesis/blob/2688a879a0450379c71eb0e5978d2557ab0bad44/main.pdf).  The figures definitely need formatting adjustment, so if you have any suggestions, feel free to include those when you look over the text!

I also think it could stand to be a bit longer, so if there's anything you think I should expand on/isn't clear, definitely let me know.  The sensitivity test section in particular is a bit brief - there are probably things I took for granted and didn't include that aren't as clear to the person that didn't run them.

Thanks so much for all your help, and have a happy weekend!

**Comment by ZoeRichter** [comment]
Also, @munkm :)

**Comment by nsryan2** [comment]
Sure thing, almost done with this one!

**Comment by ZoeRichter** [comment]
Thanks!  I know this chapter is a longer one.

**Comment by ZoeRichter** [comment]
I received the pdf via slack, thanks!
