### ISSUE TITLE
Introduction Review

### ISSUE THREAD

**Issue by ZoeRichter** [ZoeRichter/master-thesis#8]
Hi Nathan, could you review the Intro chapter?  it's a shorter one this time.  updated main pdf [here](https://github.com/ZoeRichter/master-thesis/blob/master/main.pdf)

Thanks for all your help!

Also, @munkm

**Comment by nsryan2** [comment]
You bettcha, I'm just finishing up the results section now!

**Comment by ZoeRichter** [comment]
I received the pdf via slack, thanks!
